version: '3'

services:
  api:
    container_name: node-express-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=api
    command: /bin/sh -c "/app/wait-for-it.sh mysql:3306 --timeout=60 -- npx knex migrate:latest && npx knex seed:run"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  mysql-data:
  
